Added a "Getting started" section (#2)
Getting the project to work wasn't straight-forward; detailed instructions are badly needed for newcomers and n00bcomers

Bear in mind I'm a foreigner in JS land so please feel free to modify whatever doesn't make sense (is the double `npm install` needed? or maybe the `psc-package install` should be run automatically with a `postinstall` in `package.json` or something?)

Besides, I didn't get the project to work 100%, I still get an error, but I don't know if there's a bug in the code or if there's a missing step:

* Shell:
```
ERROR in ./index.js
Module not found: Error: Can't resolve './src/editor/main' in '/home/raziel/dev/purescript-threejs'
 @ ./index.js 8:20-48
```
* JS console:
```
index.js:8 Uncaught Error: Cannot find module "./src/editor/main"
    at webpackMissingModule (index.js:8)
    at eval (index.js:8)
    at Object../index.js (main.js:774)
    at __webpack_require__ (main.js:710)
    at main.js:762
    at main.js:765
```

Also, fixed a typo for good measure